package id.infinitelearning.KotlinSubmission.exercise4

fun main() {

    /**
     * Buatlah contoh code penggunaan try catch untuk menangani suatu kasus sesuai keinginan teman-teman
     *
     */

val nilai1 = 100;
    val nilai2 = 0;
    try {
        val hasil = nilai1 / nilai22;
        println(hasil);
    }
    catch (error : ArithmeticException)
    {
        println(error);
    }
    printlin("Setelah pengecekan"):
}